name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - task-*
      - feature-*


jobs:
  release:
    name: Release
    runs-on: arc-runner-set
    steps:                  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az acr login --username token --password ajc9zNkOsJTrGY7pdPqiEVhCqHpbGvENvq/OHDzxI2+ACRDy+W1j --name imagecontainerregistrydariusz
          az acr build --registry imagecontainerregistrydariusz --image helloacrtasks:v1 .

  