name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - task-*
      - feature-*
      - issue-*
      - poc-*


jobs:
  release:
    name: Release
    runs-on: arc-runner-set
    steps: 
      - run: |
          az acr login --username token --password ajc9zNkOsJTrGY7pdPqiEVhCqHpbGvENvq/OHDzxI2+ACRDy+W1j --name imagecontainerregistrydariusz
          az acr build --registry imagecontainerregistrydariusz --image helloacrtasks:v1 .

  